# Generated by Django 3.0.4 on 2020-03-10 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagorie',
            fields=[
                ('catagorie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('catagorie_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('location', models.TextField(blank=True, null=True)),
                ('ticket_price', models.IntegerField()),
                ('ticket_amount', models.IntegerField()),
                ('picture', models.ImageField(upload_to='img')),
                ('is_popular', models.BooleanField(default=False)),
                ('catagorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Catagorie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('purchased_date', models.DateField(auto_now=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
